### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by jasikpark** [ianklatzco/psky.app#6] opened 2023-05-03 04:47 UTC
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/10626596/235834411-3939f243-0eaf-4663-923f-cb8ba9c9f02c.png">

ty for building this sweet preview app 💜 

https://psky.app/profile/xn--u38h.jasik.xyz/post/3juses57v4627, and most urls, seem to be throwing a 500 error

<img width="651" alt="image" src="https://user-images.githubusercontent.com/10626596/235834551-fc95ad8a-9d4c-4a30-8a71-c2bc1118fe2d.png">

**Comment by ianklatzco** [comment] 2023-05-03 07:08
ty report!!! should be fixed.

god, this code is ugly. needs a rewrite.

**Comment by jasikpark** [comment] 2023-05-03 13:37
hmm i'm still seeing the same error page for that link?

**Comment by yafesdot** [comment] 2023-05-03 13:40
So the problem is something with the fxbsky.app domain. We'll take care of the situation! Thanks for the report!

**Comment by jasikpark** [comment] 2023-05-03 16:29
cool, thx for sorting it out!

**Comment by ianklatzco** [comment] 2023-05-03 17:59
either my code's bad or there's something nondeterministic with the bsky api - maybe things not hydrated every time?

**Comment by jasikpark** [comment] 2023-05-03 18:27
hmm currently loading the url in the issue description ends up redirecting me to the `staging.bsky.app` version of the url?

**Comment by ianklatzco** [comment] 2023-05-03 18:31
yeah yeah! that's a ux thing -- if ppl click the psky url, they should get to the staging.bsky.app view of the tweet

mobile ios doesn't open any kind of bsky urls in-app i think

**Comment by jasikpark** [comment] 2023-05-03 18:49
yay something made it start working again....

**Comment by ianklatzco** [comment] 2023-05-03 18:53
me c:
![image](https://user-images.githubusercontent.com/1487413/236015517-4cfd11c9-72db-4467-97a0-b69293b61997.png)
https://github.com/ianklatzco/psky.app/commit/fda2c6738a18eda84ab79ca8f54d0d975f4d232b#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L264

**Closed as completed by ianklatzco** 2023-05-03 18:53 UTC

**Comment by ianklatzco** [comment] 2023-05-03 18:55
if someone wants to help out you could duplicate `generate_html_with_image` to a new `generate_html_with_image_for_external_embed` that tries pulling the image url out of an embed with `$type:external` 🥺
